version: "3"
services:
  mongodb:
    restart: unless-stopped
    container_name: mongodb
    image: mongo:5.0.1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - mongodb:/data/db
    networks:
      - backend

  mongo-express:
    restart: unless-stopped
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
    networks:
      - backend

  ruby-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "4567:4567"
    environment:
      MONGO_URL: "mongodb://mongodb:27017"
    networks:
      - backend

volumes:
  mongodb:

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.13.0/24
