development:
  clients:
    default:
      database: starship_comm_development
      hosts:
        - mongodb:27017
      options:
        user: mongodb
        password: mongodb
        auth_source: admin
  options:
    raise_not_found_error: false
    use_activesupport_time_zone: true

test:
  clients:
    default:
      database: starship_comm_test
      hosts:
        - mongodb:27017
      options:
        user: mongodb
        password: mongodb
        auth_source: admin
  options:
    raise_not_found_error: false
    use_activesupport_time_zone: true

production:
  clients:
    default:
      database: starship_comm_production
      hosts:
        - mongodb:27017
      options:
        user: mongodb
        password: mongodb
        auth_source: admin
  options:
    raise_not_found_error: false
    use_activesupport_time_zone: true
