name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0.1
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Ruby Docker image with Nix
      run: docker pull deborabe/nix-direnv-image:latest

    - name: Remove existing Ruby container if exists
      run: |
        if [ $(docker ps -a -q -f name=ruby-app) ]; then
          docker rm -f ruby-app
        fi

    - name: Run Ruby container
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        docker run -d --name ruby-app -e MONGODB_URI="${MONGODB_URI}" -p 3001:3000 deborabe/nix-direnv-image:latest 

